import type { Metadata } from "next";
import { Kulim_Park } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header";
import ThemeProvider from "@/providers/theme-provider";



const kulimPark = Kulim_Park({ subsets: ["latin"], weight: ['400', '700']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kulimPark.className}>
        <ThemeProvider attribute='class' defaultTheme ="system" enableSystem >
        <Header />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
